org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.vfs.watch=false
org.gradle.jvmargs=-Xmx2048m -Xms512m -XX:+UseG1GC -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx1536m -XX:+UseG1GC
kotlin.incremental=true
android.useAndroidX=true
android.nonTransitiveRClass=true
